export const drawMode = {
  ARROW: 'arrow',
  CIRCLE: 'circle', 
  CLEAR: 'clear',
  CUBIC: 'cubic', 
  DRAW: 'draw', 
  ELLIPSE: 'ellipse', 
  LINE: 'line', 
  MOVE: 'MOVE',
  POLYGON: 'polygon',
  POLYLINE: 'polyline', 
  QUADRATIC: 'quadratic',
  RECTANGLE: 'rect', 
  TEXT: 'text', 
}
